name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  uuid: ^3.0.6
  sqlite3: ^1.7.2
  http: ^0.13.4
  io: ^1.0.3
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
